name: "Ruby on Rails CI"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    # note: ubuntu-latest should already have Ruby 2.7.0p0 installed
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#language-and-runtime
    env:
      GEM_PATH: /home/runner/work/ci-example-mac/ci-example-mac/gem-path
      GEM_HOME: /home/runner/work/ci-example-mac/ci-example-mac/gem-path
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: gem install rails
      - run: bin/rails db:schema:load
      - run: gem install rake
      - run: bin/rake
      - run: gem install rubocop
      - run: bin/rubocop
      - run: gem install bundler-audit
      - run: bin/bundler-audit
      - run: gem install brakeman
      - run: bin/brakeman
